name: Java CI with Maven - Deploy Snapshot

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Deploy on Github
        run: SIGN_KEY=${{secrets.GPG_SECRET_KEYS}} SIGN_KEY_PASS=$(echo ${{secrets.GPG_PASSPHRASE}} | base64 --decode) ./mvnw -DaltDeploymentRepository=ossrh::https://maven.pkg.github.com/${{ github.repository }} --no-transfer-progress -B deploy -Dversioning.disable=false --file pom.xml
        if: github.repository_owner != 'tisoft'
        env:
          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_PASSWORD: ${{ github.token }}
      - name: Deploy on OSSRH
        run: SIGN_KEY=${{secrets.GPG_SECRET_KEYS}} SIGN_KEY_PASS=$(echo ${{secrets.GPG_PASSPHRASE}} | base64 --decode) ./mvnw --no-transfer-progress -B deploy -Dversioning.disable=false --file pom.xml
        if: github.repository_owner == 'tisoft'
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      - name: tag as latest
        if: github.ref_name == 'main'
        run: git tag -f latest
      - name: push latest tag
        if: github.ref_name == 'main'
        run: git push -f origin latest
      - name: Extract release notes
        if: github.ref_name == 'main'
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1
        with:
          prerelease: true
      - name: Prerelease
        if: github.ref_name == 'main'
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
          files: |
            saic-java-api-cli/target/ismart-api-cli-*-full.jar
            saic-java-api-gateway/target/ismart-api-gateway-*-full.jar
            saic-java-mqtt-gateway/target/ismart-mqtt-gateway-*-full.jar
          prerelease: true
          tag_name: latest
