name: Java CI with Maven - Deploy Snapshot

on:
  push:
    branches:
      - '**'
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      GITHUB_ACTOR: ${{ github.actor }}
      GITHUB_TOKEN: ${{ github.token }}
      OSSRH_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - name: Install tools from asdf config
        uses: ai/asdf-cache-action@v1
      - name: set java home
        run: echo "JAVA_HOME=$(dirname $( cd -P "$( dirname "$(asdf which java)" )" && pwd ))" >> $GITHUB_ENV
      - id: lowercase-repository-owner
        name: lowercase repository owner
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository_owner }}
      - uses: s4u/maven-settings-action@v2.8.0
        if: env.DOCKERHUB_USERNAME == null
        with:
          servers: '[{"id": "ossrh", "username": "${env.OSSRH_USERNAME}", "password": "${env.OSSRH_PASSWORD}"},
                     {"id": "ghcr.io", "username": "${env.GITHUB_ACTOR}", "password": "${env.GITHUB_TOKEN}"}]'
      - uses: s4u/maven-settings-action@v2.8.0
        if: env.DOCKERHUB_USERNAME != null
        with:
          servers: '[{"id": "ossrh", "username": "${env.OSSRH_USERNAME}", "password": "${env.OSSRH_PASSWORD}"},
                     {"id": "ghcr.io", "username": "${env.GITHUB_ACTOR}", "password": "${env.GITHUB_TOKEN}"},
                     {"id": "registry-1.docker.io", "username": "${env.DOCKERHUB_USERNAME}", "password": "${env.DOCKERHUB_PASSWORD}"}]'
      - name: Show settings
        run: cat ~/.m2/settings.xml
      - name: Deploy
        run: SIGN_KEY=${{ secrets.GPG_SECRET_KEYS }} SIGN_KEY_PASS=$(echo ${{ secrets.GPG_PASSPHRASE }} | base64 --decode) ./mvnw --no-transfer-progress -B deploy -Dgithub.repository=${{ github.repository }} -Dversioning.disable=false -Ddist.oci.registry=ghcr.io/${{ steps.lowercase-repository-owner.outputs.lowercase }}/ -P native
      - name: tag main branch as latest
        if: github.ref_name == 'main'
        run: git tag -f latest
      - name: push latest tag
        if: github.ref_name == 'main'
        run: git push -f origin latest
      - name: Extract release notes
        if: github.ref_name == 'main' || github.ref_type == 'tag'
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1
        with:
          prerelease: ${{ github.ref_type != 'tag' }}
      - name: Release
        if: github.ref_name == 'main' || github.ref_type == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
          files: |
            saic-java-api-cli/target/ismart-api-cli-*-full.jar
            saic-java-api-gateway/target/ismart-api-gateway-*-full.jar
            saic-java-mqtt-gateway/target/ismart-mqtt-gateway-*-full.jar
          prerelease: ${{ github.ref_type != 'tag' }}
          tag_name: ${{ github.ref_type == 'tag' && github.ref_name || 'latest' }}
