name: Java CI with Maven - Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build with Maven
        run: ./mvnw --no-transfer-progress -B verify -Dversioning.disable=false
      - name: Extract release notes
        if: github.ref_name == 'main'
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1
        with:
          prerelease: true
      - name: Prerelease
        if: github.ref_name == 'main'
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
          files: |
            saic-java-api-cli/target/ismart-api-cli-*-full.jar
            saic-java-api-gateway/target/ismart-api-gateway-*-full.jar
            saic-java-mqtt-gateway/target/ismart-mqtt-gateway-*-full.jar
          prerelease: true
          tag_name: latest
